version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3306

  app:
    image: hosniyahyaoui123/hosniimagespring
    ports:
       - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/db?autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
